spring.application.name=BRE

# Render sets PORT automatically
server.port=${PORT:8080}

# my sql
spring.datasource.url=jdbc:mysql://localhost:3306/bre
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=12345678

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql = false
spring.jpa.defer-datasource-initialization=true

# Enable H2 console (optional for debugging)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# tax and shipping rate
app.order.tax-rate = 0.07
app.order.shipping-rate = 10.00

# max items can you add it to cart
app.cart.max-cart-items = 10

# min amount for free shipping
app.order.free-shipping = 200

